<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// FIXED PATHS: Look for PHPMailer one level up from the /api folder
require __DIR__ . '/../PHPMailer/src/Exception.php';
require __DIR__ . '/../PHPMailer/src/PHPMailer.php';
require __DIR__ . '/../PHPMailer/src/SMTP.php';

if ($_SERVER["REQUEST_METHOD"] == "POST") {

    // Sanitize inbound inputs
    $name = htmlspecialchars(strip_tags(trim($_POST['name'])));
    $email = filter_var(trim($_POST['email']), FILTER_SANITIZE_EMAIL);
    $phone = htmlspecialchars(strip_tags(trim($_POST['phone'])));
    $track = htmlspecialchars(strip_tags(trim($_POST['track'])));
    $message = nl2br(htmlspecialchars(strip_tags(trim($_POST['message']))));

    $mail = new PHPMailer(true);

    try {
        // --- Server Configuration Setup ---
        $mail->isSMTP();
        $mail->Host = 'smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'ernestjulio02@gmail.com';

        // SECURE UPGRADE: Uses a Vercel environment variable if present, falls back to raw string locally
        $mail->Password = getenv('GMAIL_APP_PASSWORD') ? getenv('GMAIL_APP_PASSWORD') : 'nsqm rcko guqu nhmk';

        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port = 587;

        // --- Recipient Addressing ---
        $mail->setFrom('ernestjulio02@gmail.com', 'MGIC Portal Inquiry Hub');
        $mail->addAddress('ernestjulio02@gmail.com'); // FIXED: Explicitly added the destination recipient inbox!
        $mail->addReplyTo($email, $name);

        // --- Content Structural Styling Layout ---
        $mail->isHTML(true);
        $mail->Subject = "New Academic Inquiry - Core Portal Cluster [ " . $track . " ]";

        // Beautiful Premium HTML Template for Institutional Reading
        $mail->Body = "
        <div style='background-color: #f8fafc; padding: 40px 20px; font-family: sans-serif; color: #0f172a;'>
            <div style='max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);'>
                <div style='background-color: #1e3a8a; padding: 24px; text-align: center; border-bottom: 4px solid #f97316;'>
                    <h2 style='color: #ffffff; margin: 0; text-transform: uppercase; font-size: 18px; letter-spacing: 1px;'>Moreh Global Innovative College</h2>
                    <span style='color: #f97316; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px;'>Admissions Desk Routing</span>
                </div>
                <div style='padding: 32px;'>
                    <p style='font-size: 14px; color: #64748b; margin-top: 0;'>A clean structural profile record has been generated by a website viewer:</p>
                    
                    <table style='width: 100%; border-collapse: collapse; margin: 24px 0; font-size: 13px;'>
                        <tr>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; width: 35%; font-weight: bold;'>Inquirer Name:</td>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 600;'>{$name}</td>
                        </tr>
                        <tr>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: bold;'>Email Channel:</td>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #1e3a8a; font-weight: 600;'>{$email}</td>
                        </tr>
                        <tr>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: bold;'>Mobile Matrix:</td>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 600;'>{$phone}</td>
                        </tr>
                        <tr>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #64748b; font-weight: bold;'>Academic Path:</td>
                            <td style='padding: 10px 0; border-bottom: 1px solid #f1f5f9; color: #f97316; font-weight: bold;'>{$track}</td>
                        </tr>
                    </table>

                    <div style='background-color: #f8fafc; border-left: 4px solid #1e3a8a; padding: 16px; border-radius: 0 8px 8px 0;'>
                        <p style='margin: 0 0 8px 0; font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: bold;'>Message Context:</p>
                        <p style='margin: 0; font-size: 13px; line-height: 1.6; color: #334155;'>{$message}</p>
                    </div>
                </div>
                <div style='background-color: #0f172a; padding: 16px; text-align: center; font-size: 10px; color: #94a3b8;'>
                    © 2026 MGIC Automated Portal System Framework.
                </div>
            </div>
        </div>";

        $mail->send();
        // Redirect back smoothly to root-level layouts
        header("Location: ../inquiry.php?status=success");
        exit();

    } catch (Exception $e) {
        header("Location: ../inquiry.php?status=error");
        exit();
    }
} else {
    header("Location: ../inquiry.php");
    exit();
}